version: '3.8'
services:
  nerf-rabbit:
    container_name: rabbit-stomp
    image: tronxi/rabbit-stomp
    build:
      context: ./rabbitmq/
    ports:
      - "15672:15672"
      - "5672:5672"
      - "61613:61613"
    env_file: .env
    networks:
      - nerf-arduino-net

networks: 
    nerf-arduino-net:
